// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9I2KGxie9kvH9ECL1RNLcYuwx-nwSHxg',
    appId: '1:602090383444:web:43c6fa86cc118b3a7c65c1',
    messagingSenderId: '602090383444',
    projectId: 'praguns-new-app',
    authDomain: 'praguns-new-app.firebaseapp.com',
    storageBucket: 'praguns-new-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFYDl5oiH9bPm8KeOVZtuMRwQIOJPKMJw',
    appId: '1:602090383444:android:22deb2b042c4aa507c65c1',
    messagingSenderId: '602090383444',
    projectId: 'praguns-new-app',
    storageBucket: 'praguns-new-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS54TJk2aEK3ioPF91VTdg72tpbStpvDc',
    appId: '1:602090383444:ios:1b5390b419e36d8a7c65c1',
    messagingSenderId: '602090383444',
    projectId: 'praguns-new-app',
    storageBucket: 'praguns-new-app.appspot.com',
    iosClientId: '602090383444-9ar2c171bli2ddn0g1nhfmon9p0u8ur3.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );
}
